- platform: gree
  # required settings:
  name: First AC
  host: <ip of your first AC>
  mac: '<mac address of your first AC>'
  # optional settings:
  port: 7000
  timeout: 10
  hvac_modes: ['auto', 'dry', 'cool', 'fan_only', 'heat', 'off']
  fan_modes: ['auto' ,'low', 'medium_low', 'medium', 'medium_high', 'high', 'quiet', 'turbo']
  swing_modes: ['default', 'swing_full', 'fixed_upmost', 'fixed_middle_up', 'fixed_middle', 'fixed_middle_low', 'fixed_lowest', 'swing_downmost', 'swing_middle_low', 'swing_middle', 'swing_middle_up', 'swing_upmost']
  swing_horizontal_modes: ['default', 'swing_full', 'fixed_leftmost', 'fixed_middle_left', 'fixed_middle', 'fixed_middle_right', 'fixed_rightmost']
  temp_sensor_offset: <input_boolean for temperature sensor offset in first AC room>

- platform: gree
  # required settings:
  name: Second AC
  host: <ip of your second AC>
  mac: '<mac address of your second AC>'
  # optional settings:
  port: 7000
  timeout: 10
