"""Constants for Gree integration."""

DEFAULT_PORT = 7000
DEFAULT_TIMEOUT = 30
DEFAULT_TARGET_TEMP_STEP = 1
DEFAULT_UID = 0
DEFAULT_ENCRYPTION_VERSION = 1

MIN_TEMP_C = 16
MAX_TEMP_C = 30

MIN_TEMP_F = 61
MAX_TEMP_F = 86

TEMSEN_OFFSET = 40
