name: Validate

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest/
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: "actions/checkout@v6"

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Run HACS validation
        uses: hacs/action@22.5.0
        with:
          category: integration